name: Deploy to Another Repo

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Clone Target Repository
        run: |
          git clone -b actions-test https://github.com/sasank-pankam/PeerConnect.git target-repo
          cd target-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Setup environment
        run: |
          ls src/webpage || mkdir src/webpage

      - name: Copy Build Files
        run: |

          rm -rf target-repo/src/webpage/*
          cp -r dist/* target-repo/src/webpage/

      - name: Push Changes to Target Repo
        run: |
          cd target-repo
          git add .
          git commit -m "Deploy updated build from test branch"
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/YOUR_USERNAME/YOUR_TARGET_REPO.git main
